name: hostels
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_datepicker: ^25.1.37
  intl: ^0.19.0
  syncfusion_flutter_barcodes: ^25.1.37
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.7
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  transparent_image: ^2.0.1
  go_router: ^14.0.2
  url_launcher: ^6.2.5
  pdf: ^3.10.8
  path_provider: ^2.1.2
  document_file_save_plus: ^2.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  open_file: ^3.3.2
  awesome_snackbar_content: ^0.1.3
  flutter_image_compress: ^2.2.0
  firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.25.0
  connectivity_plus: ^6.0.3
  flutter_html: ^3.0.0-beta.2


flutter_jpeg_image: ^0.1.0
url_launcher: ^6.1.14
internet_connection_checker: ^1.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_svg: ^2.0.10+1
  flutter_lints: ^3.0.1
  google_fonts: ^6.1.0
  flutter_translate: ^4.0.4
  mask_text_input_formatter: ^2.8.0
  flutter_localization: ^0.2.0
  gap: ^3.0.1
  pinput: ^4.0.0
  mobkit_dashed_border: ^0.0.5


flutter:


  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/
    - assets/images/
    - assets/fonts/


